const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getAuthState: () => ipcRenderer.invoke('get-auth-state'),
  registerUser: (payload) => ipcRenderer.invoke('register-user', payload),
  loginUser: (payload) => ipcRenderer.invoke('login-user', payload),
  logoutUser: () => ipcRenderer.invoke('logout-user'),
  resetPassword: (payload) => ipcRenderer.invoke('reset-password', payload),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  searchMovieSources: (params) => ipcRenderer.invoke('search-movie-sources', params),
  searchEpisodeSources: (params) => ipcRenderer.invoke('search-episode-sources', params),
  testProwlarrConnection: (prowlarrConfig) => ipcRenderer.invoke('test-prowlarr-connection', prowlarrConfig),
  getProwlarrIndexers: (prowlarrConfig) => ipcRenderer.invoke('get-prowlarr-indexers', prowlarrConfig),
  getProwlarrIndexerSchemas: (prowlarrConfig) => ipcRenderer.invoke('get-prowlarr-indexer-schemas', prowlarrConfig),
  testProwlarrIndexer: (prowlarrConfig, indexerResource) => ipcRenderer.invoke('test-prowlarr-indexer', prowlarrConfig, indexerResource),
  addProwlarrIndexer: (prowlarrConfig, indexerResource) => ipcRenderer.invoke('add-prowlarr-indexer', prowlarrConfig, indexerResource),
  deleteProwlarrIndexer: (prowlarrConfig, indexerId) => ipcRenderer.invoke('delete-prowlarr-indexer', prowlarrConfig, indexerId),
  selectProwlarrExecutable: () => ipcRenderer.invoke('select-prowlarr-executable'),
  startManagedProwlarr: (prowlarrConfig) => ipcRenderer.invoke('start-managed-prowlarr', prowlarrConfig),
  stopManagedProwlarr: () => ipcRenderer.invoke('stop-managed-prowlarr'),
  getManagedProwlarrStatus: () => ipcRenderer.invoke('get-managed-prowlarr-status'),

  // Torrent APIs
  torrentAdd: (opts) => ipcRenderer.invoke('torrent-add', opts),
  torrentPrepare: (opts) => ipcRenderer.invoke('torrent-prepare', opts),
  torrentGetFiles: (id) => ipcRenderer.invoke('torrent-get-files', id),
  torrentSelectFiles: (id, fileIndexes, resume) => ipcRenderer.invoke('torrent-select-files', id, fileIndexes, resume),
  torrentGetStatus: (id) => ipcRenderer.invoke('torrent-get-status', id),
  torrentGetAll: () => ipcRenderer.invoke('torrent-get-all'),
  torrentPause: (id) => ipcRenderer.invoke('torrent-pause', id),
  torrentResume: (id) => ipcRenderer.invoke('torrent-resume', id),
  torrentRemove: (id, deleteFiles) => ipcRenderer.invoke('torrent-remove', id, deleteFiles),
  torrentGetSpeedLimit: () => ipcRenderer.invoke('torrent-get-speed-limit'),
  torrentSetSpeedLimit: (kbps) => ipcRenderer.invoke('torrent-set-speed-limit', kbps),
  torrentGetSettings: () => ipcRenderer.invoke('torrent-get-settings'),
  torrentSaveSettings: (settings) => ipcRenderer.invoke('torrent-save-settings', settings),
  openTorrentVideo: (payload) => ipcRenderer.invoke('open-torrent-video', payload),
  scanLibrary: () => ipcRenderer.invoke('library-scan'),
  openLibraryVideo: (payload) => ipcRenderer.invoke('open-library-video', payload),
  getLibraryMetadata: (filePaths) => ipcRenderer.invoke('library-metadata-get', filePaths),
  upsertLibraryMetadata: (payload) => ipcRenderer.invoke('library-metadata-upsert', payload),
  validateTorrentCandidate: (payload) => ipcRenderer.invoke('torrent-validate-candidate', payload),
  getLogs: () => ipcRenderer.invoke('logs-get'),
  clearLogs: () => ipcRenderer.invoke('logs-clear'),
  qbittorrentAdd: (opts, qbConfig) => ipcRenderer.invoke('qbittorrent-add', opts, qbConfig),
  selectDownloadDir: () => ipcRenderer.invoke('select-download-dir'),
  getDownloadDir: () => ipcRenderer.invoke('get-download-dir'),
});
